### ISSUE TITLE
CI should reject #if 1

### ISSUE THREAD

**Issue by takev** [hikogui/hikogui#259]
`#if 1` is used to temporarily enable debugging in release builds.
The CI should reject "pushes" to main when this is in the source code.

**Comment by jakoch** [comment]
The CI system cannot reject 'pushes' to the main branch based on text in the 'push.' This is because, by the time a 'git push' command is executed on the developer's machine, the push is already in the repository. The CI system operates on the server side and is triggered after the code has been pushed to the repository. You would need additional event handling on the git layer of your CI platform to handle this case on the server side.

**CI only, using workflow conditions)**:
I don't know of any CI system (Jenkins, Travis CI, CircleCI, Woodpecker, GitLab, GitHub Actions) capable of using a workflow condition (of a feature branch) as a branch protection rule (for main). I could imagine that this might work with a self-hosted buildbot, which is Python-based and scriptable. But, in general, you cannot block the push or merge to the main based on a workflow condition using CI alone.

**Server-side git hooks**: 
Free CI services do not expose access to the git layer. This feature is only available on the paid plan, as far as I know, or by self-hosting the CI platform. For example, [Github Actions Enterprise - pre-receive-hook](https://docs.github.com/en/enterprise-server@3.6/admin/policies/enforcing-policy-with-pre-receive-hooks/creating-a-pre-receive-hook-script). Gitlab provides [Push Rules](https://docs.gitlab.com/ee/user/project/repository/push_rules.html) and [Server Hooks](https://docs.gitlab.com/ee/administration/server_hooks.html). This is based on [git-receive-pack](https://git-scm.com/docs/git-receive-pack) mechanism.

**Local scan using git hook**: 
One could also set up local Git Hooks to scan the source of the branch every time and then block "pre-push.". This is a repository git hook and has nothing to do with CI. It's local to the developer's machine and is used to enforce code quality.

- https://pre-commit.com/#pre-push
- https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

**Server side scan on CI, broadcast event to dev machine, block pre-push**: 
If a monitoring tool is running on the developer's machine and is capable of polling the workflow status and its environment variables, it can serve as an event signaling mechanism to enforce certain conditions on the developer's machine. This would allow you to set conditions for pre-commit or pre-push hooks on the client side. However, relying on such a tool as an event signaling mechanism makes it a point of failure and introduces complexity and dependencies. 

For example, Github to Discord, Signal, Pagerduty, then a local Discord Bot, which picks up the message and triggers a local script to set an env var for pre-push hook, which now avoids the local source-code scan and blocks the push to main.

**Configure CI to build releases in debug mode**: 
Increase build matrix and just build release builds with the debug mode turned on continuously.

**Comment by jakoch** [comment]
Alright, I wasn't aware that this feature is available in the free plan. 
I've enabled the action and tested it.

![image](https://github.com/hikogui/hikogui/assets/85608/d7594269-b886-4c4c-92e2-3bc8dbfae953)
----
![image](https://github.com/hikogui/hikogui/assets/85608/9693773f-6310-4c83-b8ad-f6b0ce5672b9)
