### ISSUE TITLE
Example with 3D interactable model 

### ISSUE THREAD

**Issue by shujaatak** [hikogui/hikogui#272]
[by @takev]

- [x] Add hole punch (alpha value) shader.
- [x] Pass alpha channel through tone-mapper shader.
- [x] Alpha composite onto the swap-chain image.
- [x] Add callback system and semaphores to let the application directly draw on the swap-chain.
- [x] Create an Vulkan example drawing onto the swap-chain.
- [x] Add documentation on how to draw directly on the swap chain.

[original by @shujaatak]
In my opinion, apart from simple examples, there is a need for an **advance example** showing both GUI (with **both custom and builtin widgets**) and also a **widget showing 3D interactable model** as this would make ttauri more appealing.

That advance example would really weigh the usefulness and easiness of using ttauri.

**Comment by takev** [comment]
TTauri definitely does not handle 3D models yet, so an advanced example is a little bit early.

Eventually there are two ways for adding 3D models:
 - Creating a 3D surface, that allows directly drawing vulkan/opengl/directx on the widget. Possibly through the operating system.
 - Adding more pipelines/shaders for drawing polygons directly, in the same way as drawing rectangles, glyphs, etc.

I can add another example that shows interaction between custom and standard widgets, that is not a problem.

**Comment by shujaatak** [comment]
ttauri would be considered a complete gui framework if and when the requested feature is added. This would open many ways for developers to use ttauri for variety of projects like gaming, video, simulations projects!

**Comment by shujaatak** [comment]
By the way, I already love ttauri! Thanks for such a great project!

**Comment by takev** [comment]
I think the proper way to do this is to have a subpass that displays a texture-map the size of an embedded 3D surface and give access to that as a frame buffer to draw into with your own pipelines.

**Comment by shujaatak** [comment]
In my opinion, ttauri would be great if it becomes 3D first with 2D Overly.

**Comment by takev** [comment]
ttauri is already 3D, but you can't just mix two different 3D scenes through each other. The biggest issue is mixing coordinate systems.

Every 3D scene will use a different coordinate system, a unit in one scene could represent a meter, or a milimeter, or a parsec. 1 unit for ttauri widgets are device independent pixels. And the elevation for widgets are rather arbitrary.

If you want to draw a 3D scene inside a widget you will need a depth buffer and somehow this has to still match ttauri, so that you draw the 3D scene above the current widget below any overlay widgets.

To mix 3D scenes you will either not overlap them, or draw in a separate framebuffer and copy the frame buffer into the buffer shown on the window. And since ttauri will overlap, there is no choice.

**Comment by shujaatak** [comment]
Can ttauri work as UI in [VulkanSceneGraph](https://github.com/vsg-dev/VulkanSceneGraph) based project?

**Comment by takev** [comment]
Here is the current idea:
- Add callbacks on gui_window to handle custom rendering directly onto the swap-chain images. These callbacks are called before ttauri will render onto the swap-chain.
- A new shader needs to be added to clear the alpha channel. With a clipping rectangle.
- A widget for custom 3D rendering.
  - This widget will have functions for getting the pixel coordinates on the window, to be used for the viewport.
  - The widget will use the callback system described earlier to forward it to the user of the custom widget.
  - The widget will punch a hole using the new shader, this will allow this widget to be part of overlay.

In this way ttauri will be drawn on top of custom drawings directly on the swap-chain image. This will work because the full-window identity shader at the end of ttauri's pipeline is the only shader that will draw into the swap-chain and does not use depth-testing.

The custom-draw-widget can punch holes into the ttauri user interface so that the custom drawing will be shown though correctly.

Going to make a project for this.

**Comment by takev** [comment]
I am thinking of adding a 3D example for release 0.8.0.

VulkanSceneGraphic is difficult to do, because I would need to figure out how to get vsg to render a frame onto a partial part of the swap chain. I have no idea where to begin with that library.

Instead I think I can do <https://github.com/SaschaWillems/Vulkan/blob/master/examples/triangle/triangle.cpp>
That one is nice, because it doesn't use many tools outside of the cpp file. I am hoping I can keep that file mostly intact.

**Comment by takev** [comment]
I made the triangle example work, it is now in "main".

I need to improve it a bit, so it is simpler to use, and I need to add a lot of comments to it, to explain how it works.
