### ISSUE TITLE
An always up-to-date Example

### ISSUE THREAD

**Issue by shujaatak** [hikogui/hikogui#337]
It would be great if an **always up-to-date example** is included in the repository to showcase **_ALL AVAILABLE_** **features**, **widgets**, and **capabilities** of the **ttauri**.

**Comment by shujaatak** [comment]
I am also waiting for this capability: 
https://github.com/ttauri-project/ttauri/issues/272
https://github.com/ttauri-project/ttauri/issues/272#issuecomment-1001243226

**Comment by takev** [comment]
ALL AVAILABLE features is going to be a very large and application. I don't think it would be handy to have such a large application as an example, since it will be difficult to find what you want to know.

At the moment ttauri_demo has most widgets and is kept up to date with the latest methods (the one in main uses co-routines to handle communication between widgets).

I have been working on #272, I have been improving the tone-mapper, but I am only one person and there are higher priority parts.

**Comment by shujaatak** [comment]
> I have been working on #272, I have been improving the tone-mapper, but I am only one person and there are higher priority parts.

Wonderful! I am anxiously waiting for it.
